### ISSUE TITLE
Error loading plugin psucontrol_tapo

### ISSUE THREAD

**Issue by Johnnii360** [dswd/OctoPrint-PSUControl-Tapo#1]
I have 2 Octoprints. On 1 it worked very well but the second one won't. The plugin can't be load and I tried many things to fix it.

Here's the log:

`2022-04-15 21:35:47,955 - octoprint.plugin.core - ERROR - Error loading plugin psucontrol_tapo
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1291, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 68, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_tapo/__init__.py", line 9, in <module>
    from .tapo import P100
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_psucontrol_tapo/tapo.py", line 4, in <module>
    from Crypto.PublicKey import RSA
ModuleNotFoundError: No module named 'Crypto'`

Crypto is installed in pip list.

I'm using on both OctoPrint 1.7.3, Python 3.7.3, OctoPi 0.18.0.

Ah and from the install log:

`2022-04-15 21:35:32,776 > Requirement already satisfied: Crypto in /home/pi/oprint/lib/python3.7/site-packages (from OctoPrint-PSUControl-Tapo==0.1.0) (1.4.1)`

**Comment by Johnnii360** [comment]
Found the issue. Hadn't 'pycryptodome' installed.
