### ISSUE TITLE
Tapo P100 Error since octoprint 

### ISSUE THREAD

**Issue by lduriez** [dswd/OctoPrint-PSUControl-Tapo#17]
Hello

After few weeks I upgrade today Octoprint to version 1.10.2 and I have the following error trying to turn on/off my tapo P100 :

```

2024-06-18 15:25:42,586 - octoprint.plugins.psucontrol - INFO - Switching PSU On
2024-06-18 15:25:42,587 - octoprint.plugins.psucontrol_tapo - INFO - Connecting to Tapo device at 192.168.1.177
2024-06-18 15:25:42,623 - octoprint.plugins.psucontrol_tapo - ERROR - Failed to initialize protocol NewProtocol
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 268, in _initialize
    protocol._initialize()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 99, in _initialize
    raise Exception("Failed to authenticate")
Exception: Failed to authenticate
2024-06-18 15:25:42,897 - octoprint.plugins.psucontrol_tapo - ERROR - Error: {'error_code': 1003}
2024-06-18 15:25:42,898 - octoprint.plugins.psucontrol_tapo - ERROR - Failed to initialize protocol OldProtocol
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 268, in _initialize
    protocol._initialize()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 232, in _initialize
    result = self._request_raw("handshake", {
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 157, in _request_raw
    raise Exception(f"Error code: {data['error_code']}")
Exception: Error code: 1003
2024-06-18 15:25:42,898 - octoprint.plugins.psucontrol_tapo - ERROR - Failed to switch PSU On
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/__init__.py", line 89, in turn_psu_on
    self.device.set_status(True)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 301, in set_status
    return self._set_device_info({"device_on": status})
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 284, in _set_device_info
    return self.request("set_device_info", params)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 277, in request
    self._initialize()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 273, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
2024-06-18 15:25:42,898 - octoprint.plugins.psucontrol - ERROR - Error while executing callback <bound method PSUControl_Tapo.turn_psu_on of <octoprint_psucontrol_tapo.PSUControl_Tapo object at 0x7187e310>>
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol/__init__.py", line 495, in turn_psu_on
    r = callback()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/__init__.py", line 89, in turn_psu_on
    self.device.set_status(True)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 301, in set_status
    return self._set_device_info({"device_on": status})
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 284, in _set_device_info
    return self.request("set_device_info", params)
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 277, in request
    self._initialize()
  File "/home/pi/oprint/lib/python3.9/site-packages/octoprint_psucontrol_tapo/tapo.py", line 273, in _initialize
    raise Exception("Failed to initialize protocol")
Exception: Failed to initialize protocol
```

My Tapo P100 firmware is up to date (1.4.10 build 20211104 rel. 35882), and python version is 3.9.2.

I hope you could help me with this.

Regards

**Comment by Naudnaud25** [comment]
Hello

Same problem with me
Same problem in log file -_-

**Comment by KaiStarkk** [comment]
+1, seems to be the latest Octoprint version is breaking

**Comment by KaiStarkk** [comment]
The issue for me was that the Username had reset to my Octoprint username. I needed to change it back to the Tapo username (which was my email address used to sign up to Tapo).

**Comment by SilkierLyric146** [comment]
I'am having the same problem, any fix ??
